version: '3.9'

services:
  content:
    build: ./content
    ports:
      - "8080:8080"
    networks:
      - rede_microservicos

  users:
    build: ./users
    ports:
      - "8082:8082"
    networks:
      - rede_microservicos

  payment:
    build: ./payment
    ports:
      - "8081:8081"
    networks:
      - rede_microservicos

  frontend:
    build: ./frontend
    ports:
      - "4200:4200"
    depends_on:
      - content
      - users
    networks:
      - rede_microservicos

networks:
  rede_microservicos:
    driver: bridge
