version: '3.9'

services:
  content:
    build: ./content
    ports:
      - "8001:8000"
    networks:
      - rede_microservicos

  users:
    build: ./users
    ports:
      - "8002:8000"
    networks:
      - rede_microservicos

networks:
  rede_microservicos:
    driver: bridge
