version: '3.9'

services:
  content:
    build: ./content
    ports:
      - "8001:8000"
    networks:
      - rede_microservicos

  users:
    build: ./users
    ports:
      - "8002:8000"
    networks:
      - rede_microservicos

  frontend:
    build: ./frontend
    ports:
      - "3000:4200"
    depends_on:
      - content
      - users
    networks:
      - rede_microservicos
    
  db:
    image: postgres:16
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: users_db
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - rede_microservicos

networks:
  rede_microservicos:
    driver: bridge
